options(repos = "https://cran.ma.imperial.ac.uk/")
if (!require(magrittr)) install.packages("magrittr")
if (!require(readr)) install.packages("readr")
if (!require(readxl)) install.packages("readxl")
if (!require(lubridate)) install.packages("lubridate")
if (!require(ggplot2)) install.packages("ggplot2")
if (!require(DT)) install.packages("DT")
if (!require(knitr)) install.packages("knitr")
if (!require(rmarkdown)) install.packages("rmarkdown")
if (!require(esquisse)) install.packages("esquisse")
if (!require(devtools)) install.packages("devtools")
# if (!require(ggpomological)) devtools::install_github("gadenbuie/ggpomological")
if (!require(ggrough)) devtools::install_github("xvrdm/ggrough")
library(magrittr)
# help(package="magrittr")
library(readr)
# help(package="readr")
library(readxl)
# help(package="readxl")
library(lubridate)
# help(package="lubridate")
library(ggplot2)
# help(package="ggplot2")
library(DT)
# help(package="DT")
library(esquisse)
# library(ggpomological)
library(ggrough)
