options(repos = "https://cran.ma.imperial.ac.uk/")
install.packages("magrittr")
install.packages("dplyr")
install.packages("tidyr")
install.packages("ggplot2")
install.packages("rmarkdown")
install.packages("esquisse")
install.packages("knitr")
install.packages("DT")